publishDir: docs
baseurl: "https://agilewarsaw.github.io/ABELight/"
title: "ABE Light 2018"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: "UA-112461830-1"

params:
  # Conference info
  Name: "ABE Light 2018"
  #Description: "Conference description"
  Date: "17 marca (sobota)"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Akademia Finansów i Biznesu VISTULA"
  Address: "Stokłosy 3"
  City:  "Warszawa"
  #State: "Quintana"
  Images: ["/img/badge.jpg"]

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    - sponsors
    - partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "O konferencji"
    location: "Gdzie?"
    speakers: "Kto?"
    schedule: "Rozkład jazdy"
    sponsors: "Sponsorzy"
    partners: "Partnerzy"
    contact: "Kontakt"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
      text: "Zarejestruj się gratis"
      link: "http://"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "ProCognita"
      logo: "img/logo_procognita.png"
      url: "https://procognita.pl/"

    - name: "AZA"
      logo: "img/aza_logo_graphite_box.png"
      url: "https://azagroup.eu/o-nas/"

    - name: "Vistula"
      logo: "img/logo_vistula.jpg"
      url: "http://www.vistula.edu.pl/"
  # List of Partners
  Partners:
    - name: "Agile Warsaw"
      logo: "img/logo_AW.png"
      url: "http://agilewarsaw.com"

  # The entire schedule
  Schedule:
    - name: "Startujemy"
      time: "13h45"
      remark: "Bardzo prosimy przybywać na czas."

    - name: "Mary Poppendieck"
      photo: "img/mary.jpg"
      bio: "Wszyscy znają…"
      #company: "Linux Foundation"
      link:
        href: "http://twitter.com/linus"
        text: "@linus"
      presentation:
        title: "Promises without Proxies or Permission: Thinking Differently about Complex Systems"
        description: "Agile is well past its prime. In 2001, when Agile was a new idea, there were no smartphones, no clouds, no Internet of Things. It’s high time for some fresh thinking about managing complex software systems.

Modern software systems are created by autonomous agents (often small teams) that make promises to their customers. Their job is to deeply understand customers’ needs and frustrations, and using this understanding as a starting point, they make a promise to customers: “We will meet this need or reduce that frustration, and we promise that your experience will be better as a result.”

Working to promises removes the need for proxies – either customer experiences are improved, or not.  Autonomous agents are neither told what promises to make nor how to keep their promises. They do not concern themselves with transparency, and they don’t need permission to do things their own way.

When multiple autonomous agents work together to achieve a shared goal – as they must in a complex system – they coordinate through promises to each other. Agents do not impose obligations on each other and they promise only what is within their power to deliver. Communication about complex systems focuses on what agents need from each other and what they promise to each other.

This is the way open source systems have always been built. It is the way platforms work. It is the way Microservices should work. It is the future of the cloud and the Internet of Things. Is it your future too?"
        #time: "14h00"

    - name: "Wykowski i Ska."
      photo: "img/wykowski.jpg"
      #photo: "/img/speaker.jpg"
      bio: "bio…"
      company: "ProCognita"
      link:
        href: "http://github.com/billy95"
        text: "@billy95"
      presentation:
        title: "Warsztat"
        description: "Opis warsztatu"
        #time: "11h00"

    - name: "Lunch"
      remark: "Każdy płaci za siebie. Kantyna Vistuli da radę nas obsłużyć."

    - name: "Michał Dworczyk"
      photo: "img/dworczyk.jpg"
      bio: "bio"
      company: "firma"
      link:
        href: "http://twitter.com/woz"
        text: "@woz"
      presentation:
        title: "Tytuł"
        description: "zajawka"

    - name: "Dorota Jaworska"
      photo: "img/jaworska.jpg"
      bio: "bio"
      company: "firma"
      link:
        href: "http://twitter.com/woz"
        text: "@woz"
      presentation:
        title: "Tytuł"
        description: "zajawka"

    - name: "Marcin Gozdalik"
      photo: "img/gozdalik.jpg"
      bio: "bio"
      company: "firma"
      link:
        href: "http://twitter.com/woz"
        text: "@woz"
      presentation:
        title: "Tytuł"
        description: "zajawka"

    - name: "Afterparty"
      remark: "W pobliżu…"
      time: "~19h30"


      #    - name: "Steve Wozniak"
      #      photo: "/img/speaker.jpg"
      #      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      #      company: "Apple, Inc."
      #      link:
      #        href: "http://twitter.com/woz"
      #        text: "@woz"
      #      presentation:
      #        title: "Why do I prefer Android over iPhone"
      #        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      #        time: "17h00"
